wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.18
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.10.2
    start_time: 1655442046
    t:
      1:
      - 1
      - 41
      - 55
      2:
      - 1
      - 41
      - 55
      3:
      - 13
      - 16
      4: 3.10.2
      5: 0.12.18
      8:
      - 4
      - 5
batch_size:
  desc: null
  value: 128
downloads:
  desc: null
  value: true
epochs:
  desc: null
  value: 10
h_dim:
  desc: null
  value: 32
image_size:
  desc: null
  value: 784
learning_rate:
  desc: null
  value: 1e-3
project_name:
  desc: null
  value: CVAE
roots:
  desc: null
  value: ./data
seed:
  desc: null
  value: 1234
shuffle:
  desc: null
  value: true
train:
  desc: null
  value: true
train_name:
  desc: null
  value: CVAE_tryTrain
weight:
  desc: null
  value: wb
workers:
  desc: null
  value: 0
yml:
  desc: null
  value: yml/train.yml
z_dim:
  desc: null
  value: 16
